firstname = input("Enter your First name: ")
lastname = input("Enter your Last name: ")
middlename = input("Enter your Middle name: ")
bday = input("Enter your Birthday: ")
gender = input("Enter your Gender: ")
address = input("Enter your Address: ")
course = input("Enter your Course: ")
ylevel = input("Enter your Year Level: ")

print("")
print("Name:", firstname, middlename, lastname)
print("Birthday:", bday)
print("Gender:", gender)
print("Address:", address)
print("Course:", course)
print("Year Level:", ylevel)
print("")